version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - "C:/Users/hp/Etudiant-management/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    networks:
      - app_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_USER: user
      MYSQL_PASSWORD: 0000
      MYSQL_DATABASE: etudiants
    networks:
      - app_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3

  backend:
    image: localhost:5000/spring-boot-app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/etudiants
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 0000
    networks:
      - app_network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    image: localhost:5000/react-app:latest
    networks:
      - app_network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  app_network:
    driver: overlay
